spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stockCompany?serverTimezone=UTC
    username: root
    password:
    initialization-mode: always
    
  jpa:
    hibernate.ddl-auto: update
   
  application:
    name: stock_company-service
  

server:
  port: 8305


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost